### ISSUE TITLE
VS Code extension doesn't work with v1.77.1 (March 2023)

### ISSUE THREAD

**Issue by EGAMAGZ** [tw-in-js/vscode-twind-intellisense#24]
Out of the blue, intellisense stopped working even though I installed the twind and deno extensions in VS Code. I tried it with VS Code v1.76 (February 2023) and it works perfectly

VS Code: 1.77.1
Deno: 1.32.3
Fresh: 1.1.5
Twind: 0.16.19
Initialized workspace and cached libraries: Yes
![image](https://user-images.githubusercontent.com/46827955/230442889-58ea184a-f114-4902-82e1-10ca149ab64e.png)

**Comment by dev-frid** [comment]
+1, extension is unusable for me at the moment

**Comment by HernandoPinzon** [comment]
+1, same with me, works when I downgrade the version of vscode

**Comment by jamesbradlee** [comment]
+1, still an issue

Cause:

```
2023-06-17 03:27:30.962 [error] <semantic> TypeScript Server Error (5.1.3)
this.info.project.resolveModuleNames is not a function
TypeError: this.info.project.resolveModuleNames is not a function
    at get state [as state] (/Users/t980781/.vscode/extensions/sastan.twind-intellisense-0.2.1/node_modules/@twind/typescript-plugin/typescript-plugin.cjs:662:42)
    at get enabled [as enabled] (/Users/t980781/.vscode/extensions/sastan.twind-intellisense-0.2.1/node_modules/@twind/typescript-plugin/typescript-plugin.cjs:633:32)
    at get enabled [as enabled] (/Users/t980781/.vscode/extensions/sastan.twind-intellisense-0.2.1/node_modules/@twind/typescript-plugin/typescript-plugin.cjs:1047:24)
    at Object.getQuickInfoAtPosition (/Users/t980781/.vscode/extensions/sastan.twind-intellisense-0.2.1/node_modules/@twind/typescript-plugin/typescript-plugin.cjs:1681:28)
    at IpcIOSession.getQuickInfoWorker (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:181475:52)
    at quickinfo (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:179916:43)
    at /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:182353:69
    at IpcIOSession.executeWithRequestId (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:182345:14)
    at IpcIOSession.executeCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:182353:29)
    at IpcIOSession.onMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:182395:51)
    at process.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:183975:14)
    at process.emit (node:events:513:28)
    at emit (node:internal/child_process:967:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:84:21): Error: <semantic> TypeScript Server Error (5.1.3)
```

**Comment by nomi-san** [comment]
Use `@twind/preset-tailwind` with [Tailwind CSS IntelliSense](https://marketplace.visualstudio.com/items?itemName=bradlc.vscode-tailwindcss) and an empty `tailwind.config.ts`.

**Comment by xlboy** [comment]
This is a separate [`VSCode Twind intellisense`](https://github.com/xlboy/vscode-twind-intellisense) extension that I developed, which only supports **v1**. It is still a work in progress. If you're interested, feel free to check it out.
